### ISSUE TITLE
bootstrap compatibility

### ISSUE THREAD

**Issue by mykael25** [DarKsandr/dark-editable#1]
is there a way to use this on other version of bootstrap? my page has different version of bootstrap and the page display are ruined if i try to implement the boostrap needed by the editor. or if i use other version of bootstrap the form for editing doesnt show at all, thank you and god bless!!

**Comment by DarKsandr** [comment]
which version do you want to use?

**Comment by mykael25** [comment]
bootstrap 3 because my webpage is using bootstrap 3, is there a way i can hard code the css popper so i can maintain my version of bootstrap,  and still have the pop up for editing. thank you

**Comment by DarKsandr** [comment]
For bootstrap 3 and 4 there is an original library (https://vitalets.github.io/x-editable/). This one was made for bootstrap 5 and to get rid of jquery

**Comment by mykael25** [comment]
thank you so much for the information i will look into it
