### ISSUE TITLE
Body Scrolls up when popup is opened.

### ISSUE THREAD

**Issue by siripravi** [DarKsandr/dark-editable#12]
When i click the link for opening editable form, the form gets opened correctly, but the page is scrolled to top, sometimes causing the editable form to not to be inaccessible.

**Comment by siripravi** [comment]
Here is the generated code for the link:
`<a id="w11" class="link-primary ps-3 link-underline-opacity-25 link-underline-opacity-100-hover dark-editable-element" href="#" data-name="address2" data-value="Lakshmi Nagar Colony" data-type="text" data-url="/invoice/contact/editable" data-pk="199" data-title="" aria-describedby="popover108605">Lakshmi Nagar Colony</a>`

**Comment by DarKsandr** [comment]
@siripravi remove `href ="#"` or replace the link with another element, say span.

**Comment by siripravi** [comment]
Thank you. That did work great.
