### ISSUE TITLE
Q: Custom types

### ISSUE THREAD

**Issue by jaroslavlibal** [DarKsandr/dark-editable#2]
Hello,

I was using x-editable on an older project and now I'm looking for a maintained replacement for a new BS5 project. 

I was delighted when I discovered your library. But I would like to ask - how about the possibility of extending with custom types? Within x-editable I was used to use custom types - e.g. for address (composed of multiple inputs), inputmask, etc. Is this possible with your implementation? So far it seems to me that unfortunately not.

Thanks!

**Comment by DarKsandr** [comment]
Could you please provide a code example as i didn't find any examples of custom types in the x-editable documentation? Or give a link where it is in the documentation

**Comment by jaroslavlibal** [comment]
I'm not sure if the documentation mentions this, but in the official examples it is used when editing the address:
https://vitalets.github.io/x-editable/demo-bs3.html?c=inline ( https://github.com/vitalets/x-editable/tree/develop/src/inputs-ext/address )

We have made this way e.g. date editing with inputmask, or name and surname editing (see attached links, but please disregard the quality of the code :smile: )

Custom date with inputmask (hardcoded template): https://pastebin.com/zBHjDeKV
Name and surname (custom template): https://pastebin.com/LQC7UEka

**Comment by DarKsandr** [comment]
I looked and understood what you want, but I'm not ready to say when it will be ready yet.
p.s. I liked what I saw, so I will try to implement it

**Comment by petaak** [comment]
I would also appreciate this feature. Any progress here?

**Comment by DarKsandr** [comment]
> I would also appreciate this feature. Any progress here?

Yes, work is underway, but very slowly.  this is not my main project

**Comment by DarKsandr** [comment]
@jaroslavlibal @petaak  I included the possibility of custom fields, but for now it’s crude and needs some work. You can see #9.
