### ISSUE TITLE
How to import DarkEditable as a module ?

### ISSUE THREAD

**Issue by patsch** [DarKsandr/dark-editable#3]
I've been trying to import DarkEditable as a JS module but had no luck - is it available as a node module with a defined package.json somewhere ?

**Comment by DarKsandr** [comment]
no, it is designed for plug and play (without import), but in principle it is possible to make an import version

**Comment by patsch** [comment]
Thank you, and thanks for making this available publicly. I’ll see how I go with making a node module !
