### ISSUE TITLE
How to add to weback?

### ISSUE THREAD

**Issue by mumus** [DarKsandr/dark-editable#5]
Hello. How to add your file to webpack ?

You may need an appropriate loader to handle this file type.
`|     init_options(){
|         const get_opt = (name, default_value) => {
>             return this[ name ] = this.element.dataset?.[ name ] ?? this.options?.[ name ] ?? default_value;
|         }
|         const get_opt_bool = (name, default_value) => {`

Thank you

**Comment by DarKsandr** [comment]
Добрый, изначально эта библиотека не предназначена для сборки, но вы можете немного ее дописать. Все что вам для этого требуется, это добавить импорт/экспорт в библиотеку.
Во-первых, добавим экспорт в библиотеку:
```
export default class DarkEditable{
…
}
```
Во-вторых, там где мы хотим вызвать импортируем её:
```
import DarkEditable from "./vendor/dark-editable";
new DarkEditable(document.getElementById('test'))
```
В-третьих (не обязательно если bootstrap установлен вне webpack ): нужно импортнуть класс bootstrap.Popover

---
Good, initially this library is not intended for assembly, but you can add it a little. All you need to do is add an import/export to the library. 
First, let's add an export to the library:
```
export default class DarkEditable{
…
}
```
Secondly, where we want to call it, we import it:
```
import DarkEditable from "./vendor/dark-editable";
new DarkEditable(document.getElementById('test'))
```
Thirdly (not necessary if bootstrap is installed outside of webpack): you need to import the bootstrap.Popover class

**Comment by mumus** [comment]
Thank you very much. It works very well!
