### ISSUE TITLE
Enable dark-editable everywhere

### ISSUE THREAD

**Issue by darkeum** [DarKsandr/dark-editable#6]
Add another way to initialize all dark-editable on a page is to select them by their data-bs-toggle attribute.
For example: 
<script>
        var editableTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="dark-editable"]'))
        var editableList = editableTriggerList.map(function(editableTriggerEl) {
            return new DarkEditable(editableTriggerEl)
        })
</script>

**Comment by DarKsandr** [comment]
You can use it on any attributes:
```
document.querySelectorAll('[data-bs-toggle="dark-editable"]').forEach(el => {
    new DarkEditable(el);
})
```

**Comment by darkeum** [comment]
I also understand this, but I suggest adding this to the documentation for a quick start
