### ISSUE TITLE
In-place editing ?

### ISSUE THREAD

**Issue by Awsom3D** [DarKsandr/dark-editable#7]
Hi,

Thank you for your work this looks very promising. I'm considering replacing x-editable in our website by your code.
One thing I couldn't find in the readme nor demo ; does it support in-place editing as x-editable ?

Thank you very much,

PS: There is some typos in the README (CTRL+F "examole", "Usefull") and in the demo ("Sate of Birth").

**Comment by DarKsandr** [comment]
What is meant by "support in-place editing"? Local change without sending to the server?  Yes it is available, in the readme you can find it as: "Work LOCALLY".

**Comment by Awsom3D** [comment]
No I meant without opening a popup. Exactly like when you edit a previous comment on github.
In x-editable demo, you can select the mode "inline" instead of default "popup"
https://vitalets.github.io/x-editable/demo-bs3.html?c=inline
